---
# Group & Users creation for automation Team

- name: Add automation User Group
  group:
    name: automation
    state: present
    
- name: Add ansible User
  user:
    name: "{{ automation_user }}"
    create_home: true
    generate_ssh_key: true
    password: "{{ 'automation_password' | password_hash('sha512') }}"
 #   update_password: on_create
    group: automation

- name: Add ansible user to the sudoers
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
    
- name: Copy ansible config template
  template:
    src: ansible-cfg.j2
    dest: /etc/ansible/ansible.cfg
    backup: true
  delegate_to: localhost
#  when: "{{ automation_vm }}" == "true"
